#ifndef __MESSAGE_DEFINES_VIDEOCHAT_H__
#define __MESSAGE_DEFINES_VIDEOCHAT_H__

#define MXP_MAINCMD_VIDEOCHAT  102

#define MXP_SUBCMD_VIDEOCHAT_USERLOGON_REQ       1001
#define MXP_SUBCMD_VIDEOCHAT_USERLOGON_RESP      1002

#define MXP_SUBCMD_VIDEOCHAT_JOINROOM_REQ        1011
#define MXP_SUBCMD_VIDEOCHAT_JOINROOM_RESP       1012

#define MXP_SUBCMD_VIDEOCHAT_JOINROOM_FINISH     1013

#define MXP_SUBCMD_VIDEOCHAT_ROOMINFO_NOTY       1014
#define MXP_SUBCMD_VIDEOCHAT_ROOMNOTICE_NOTY     1015
#define MXP_SUBCMD_VIDEOCHAT_ROOMMICSTATE_NOTY   1016
#define MXP_SUBCMD_VIDEOCHAT_FLYGIFTRECORD_NOTY  1017

#define MXP_SUBCMD_VIDEOCHAT_ROOMUSERLIST_BEGIN  1018
#define MXP_SUBCMD_VIDEOCHAT_ROOMUSERLIST_DATA   1019
#define MXP_SUBCMD_VIDEOCHAT_ROOMUSERLIST_END    1020

#define MXP_SUBCMD_VIDEOCHAT_ROOMCHATMSG_REQ     1021
#define MXP_SUBCMD_VIDEOCHAT_ROOMCHATMSG_RESP    1022
#define MXP_SUBCMD_VIDEOCHAT_ROOMCHATMSG_NOTY    1023

#define MXP_SUBCMD_VIDEOCHAT_ROOMSENDGIFT_REQ    1024
#define MXP_SUBCMD_VIDEOCHAT_ROOMSENDGIFT_RESP   1025
#define MXP_SUBCMD_VIDEOCHAT_ROOMSENDGIFT_NOTY   1026

#define MXP_SUBCMD_VIDEOCHAT_ROOMUPMIC_REQ       1027
#define MXP_SUBCMD_VIDEOCHAT_ROOMUPMIC_RESP      1028
#define MXP_SUBCMD_VIDEOCHAT_ROOMUPMIC_NOTY

#define MXP_SUBCMD_VIDEOCHAT_ROOMDOWNMIC_REQ     1029
#define MXP_SUBCMD_VIDEOCHAT_ROOMDOWNMIC_RESP    1030
#define MXP_SUBCMD_VIDEOCHAT_ROOMDOWNMIC_NOTY    1031

#define MXP_SUBCMD_VIDEOCHAT_ROOMPAIMIC_REQ      1032
#define MXP_SUBCMD_VIDEOCHAT_ROOMPAIMIC_RESP     1033
#define MXP_SUBCMD_VIDEOCHAT_ROOMPAIMIC_END      1034

#define MXP_SUBCMD_VIDEOCHAT_EXITROOM_REQ        1035
#define MXP_SUBCMD_VIDEOCHAT_EXITROOM_RESP       1036
#define MXP_SUBCMD_VIDEOCHAT_EXITROOM_NOTY       1037

#define MXP_SUBCMD_VIDEOCHAT_ROOMKICKOUTUSER_REQ   1038
#define MXP_SUBCMD_VIDEOCHAT_ROOMKICKOUTUSER_RESP  1039
#define MXP_SUBCMD_VIDEOCHAT_ROOMKICKOUTUSER_NOTY  1040

#define MXP_SUBCMD_VIDEOCHAT_SETROOMINFO_REQ       1041
#define MXP_SUBCMD_VIDEOCHAT_SETROOMINFO_RESP      1042

#define MXP_SUBCMD_VIDEOCHAT_SETROOMNOTICE_REQ     1043
#define MXP_SUBCMD_VIDEOCHAT_SETROOMNOTICE_RESP    1044

#define MXP_SUBCMD_VIDEOCHAT_SETUSERINFO_REQ       1045
#define MXP_SUBCMD_VIDEOCHAT_SETUSERINFO_RESP      1046

#define MXP_SUBCMD_VIDEOCHAT_ROOMADDMGR_REQ        1047
#define MXP_SUBCMD_VIDEOCHAT_ROOMADDMGR_RESP       1048
#define MXP_SUBCMD_VIDEOCHAT_ROOMADDMGR_NOTY       1049

#define MXP_SUBCMD_VIDEOCHAT_ROOMDELMGR_REQ        1050
#define MXP_SUBCMD_VIDEOCHAT_ROOMDELMGR_RESP       1051
#define MXP_SUBCMD_VIDEOCHAT_ROOMDELMGR_NOTY       1052
 
#define MXP_SUBCMD_VIDEOCHAT_ROOMNB2NK_REQ         1053
#define MXP_SUBCMD_VIDEOCHAT_ROOMNB2NK_RESP        1054

#define MXP_SUBCMD_VIDEOCHAT_ROOMTRANSFER_REQ      1055
#define MXP_SUBCMD_VIDEOCHAT_ROOMTRANSFER_RESP     1056
#define MXP_SUBCMD_VIDEOCHAT_ROOMTRANSFER_NOTY     1057

#define MXP_SUBCMD_VIDEOCHAT_ROOMNB2RMB_REQ        1058
#define MXP_SUBCMD_VIDEOCHAT_ROOMNB2RMB_RESP       1059

#define MXP_SUBCMD_VIDEOCHAT_ROOMKEEPLIVE_REQ      1060
#define MXP_SUBCMD_VIDEOCHAT_ROOMKEEPLIVE_RESP     1061

#define MXP_SUBCMD_VIDEOCHAT_LOTTERY_XINYUN_NOTY   1062
#define MXP_SUBCMD_VIDEOCHAT_LOTTERY_BAOZHA_NOTY   1063

#define MXP_SUBCMD_VIDEOCHAT_ROOMUSERCOMEIN_NOTY   1064
 
#define MXP_SUBCMD_VIDEOCHAT_USERACCOUNT_REQ       1065
#define MXP_SUBCMD_VIDEOCHAT_USERACCOUNT_RESP      1066
#define MXP_SUBCMD_VIDEOCHAT_USERACCOUNT_NOTY      1067

#define MXP_SUBCMD_VIDEOCHAT_ROOMADDMUTEUSER_REQ   1068
#define MXP_SUBCMD_VIDEOCHAT_ROOMADDMUTEUSER_RESP  1069
#define MXP_SUBCMD_VIDEOCHAT_ROOMADDMUTEUSER_NOTY  1070

#define MXP_SUBCMD_VIDEOCHAT_ROOMDELMUTEUSER_REQ   1071
#define MXP_SUBCMD_VIDEOCHAT_ROOMDELMUTEUSER_RESP  1072
#define MXP_SUBCMD_VIDEOCHAT_ROOMDELMUTEUSER_NOTY  1073

#define MXP_SUBCMD_VIDEOCHAT_ROOMADDBALCKUSER_REQ  1074
#define MXP_SUBCMD_VIDEOCHAT_ROOMADDBLACKUSER_RESP 1075
#define MXP_SUBCMD_VIDEOCHAT_ROOMADDBLACKUSER_NOTY 1076

#define MXP_SUBCMD_VIDEOCHAT_ROOMDELBALCKUSER_REQ  1077
#define MXP_SUBCMD_VIDEOCHAT_ROOMDELBLACKUSER_RESP 1078
#define MXP_SUBCMD_VIDEOCHAT_ROOMDELBLACKUSER_NOTY 1079

#endif //__MESSAGE_DEFINES_VIDEOCHAT_H__

