//
//  message_defines_dpkgame.h
//  DPKGame
//
//  Created by gu  on 16/9/21.
//  Copyright © 2016年 王征. All rights reserved.
//

#ifndef message_defines_dpkgame_h
#define message_defines_dpkgame_h

#define MXP_MAINCMD_DPKGAME  103


#define MXP_SUBCMD_DPKGAME_USERLOGON_REQ  2001
#define MXP_SUBCMD_DPKGAME_USERLOGON_RESP 2002
#define MXP_SUBCMD_DPKGAME_USERLOGON_FINISHED 2003

#define MXP_SUBCMD_DPKGAME_CLUBLIST_BEGIN  2004
#define MXP_SUBCMD_DPKGAME_CLUBLIST_DATA   2005
#define MXP_SUBCMD_DPKGAME_CLUBLIST_END    2006

#define MXP_SUBCMD_DPKGAME_GAMELIST_BEGIN  2007
#define MXP_SUBCMD_DPKGAME_GAMELIST_DATA   2008
#define MXP_SUBCMD_DPKGAME_GAMELIST_END    2009

#define MXP_SUBCMD_DPKGAME_CLUBINFO_NOTY   2010
#define MXP_SUBCMD_DPKGAME_GAMEINFO_NOTY   2011

#define MXP_SUBCMD_DPKGAME_DELCLUB_NOTY    2012
#define MXP_SUBCMD_DPKGAME_DELGAME_NOTY    2013

#define MXP_SUBCMD_DPKGAME_CREATECLUB_REQ  2014
#define MXP_SUBCMD_DPKGAME_CREATECLUB_RESP 2015
#define MXP_SUBCMD_DPKGAME_CREATECLUB_NOTY 2016

#define MXP_SUBCMD_DPKGAME_DELCLUB_REQ     2017
#define MXP_SUBCMD_DPKGAME_DELCLUB_RESP    2018

#define MXP_SUBCMD_DPKGAME_CREATEGAME_REQ  2019
#define MXP_SUBCMD_DPKGAME_CREATEGAME_RESP  2020
#define MXP_SUBCMD_DPKGAME_CREATEGAME_NOTY  2021

#define MXP_SUBCMD_DPKGAME_GETUSERINFO_REQ  2022
#define MXP_SUBCMD_DPKGAME_GETUSERINFO_RESP 2023

#define MXP_SUBCMD_DPKGAME_CLUBUSER_BEGIN   2024
#define MXP_SUBCMD_DPKGAME_CLUBUSER_DATA    2025
#define MXP_SUBCMD_DPKGAME_CLUBUSER_END     2026

#define MXP_SUBCMD_DPKGAME_CLUBJOIN_REQ    2027
#define MXP_SUBCMD_DPKGAME_CLUBJOIN_RESP   2028
#define MXP_SUBCMD_DPKGAME_CLUBJOIN_NOTY   2029

#define MXP_SUBCMD_DPKGAME_CLUBEXIT_REQ    2030
#define MXP_SUBCMD_DPKGAME_CLUBEXIT_RESP   2031
#define MXP_SUBCMD_DPKGAME_CLUBEXIT_NOTY   2032

#define MXP_SUBCMD_DPKGAME_CLUBKICKOUT_REQ  2033
#define MXP_SUBCMD_DPKGAME_CLUBKICKOUT_RESP 2034
#define MXP_SUBCMD_DPKGAME_CLUBKICKOUT_NOTY 2035


#endif /* message_defines_dpkgame_h */
